.TH "AbstractGame" 3 "Mon Jan 1 2018" "MGE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AbstractGame
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AbstractGame\&.hpp>\fP
.PP
Inherited by \fBdemo::MGEDemo\fP, \fBMyEngine::MGEDemo\fP, and \fBMyGame::MGEDemo\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAbstractGame\fP ()"
.br
.ti -1c
.RI "virtual \fB~AbstractGame\fP ()"
.br
.ti -1c
.RI "virtual void \fBinitialize\fP ()"
.br
.ti -1c
.RI "virtual void \fBrun\fP ()"
.br
.RI "MAIN GAME LOOP\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fB_initializeWindow\fP ()"
.br
.RI "SETUP\&. "
.ti -1c
.RI "virtual void \fB_printVersionInfo\fP ()"
.br
.ti -1c
.RI "virtual void \fB_initializeGlew\fP ()"
.br
.ti -1c
.RI "virtual void \fB_initializeRenderer\fP ()"
.br
.ti -1c
.RI "virtual void \fB_initializeWorld\fP ()"
.br
.ti -1c
.RI "virtual void \fB_initializeScene\fP ()=0"
.br
.ti -1c
.RI "virtual void \fB_update\fP (float pStep)"
.br
.ti -1c
.RI "virtual void \fB_render\fP ()"
.br
.ti -1c
.RI "virtual void \fB_processEvents\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "sf::RenderWindow * \fB_window\fP"
.br
.ti -1c
.RI "\fBRenderer\fP * \fB_renderer\fP"
.br
.ti -1c
.RI "\fBWorld\fP * \fB_world\fP"
.br
.ti -1c
.RI "float \fB_fps\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines the basic structure for a game, with defaults already filled in\&. The only item that MUST be overridden/implemented is \fB_initializeScene()\fP where you build up your world, the rest is optional to override (with care/caution)\&. 
.PP
Definition at line 16 of file AbstractGame\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AbstractGame::AbstractGame ()"

.PP
Definition at line 7 of file AbstractGame\&.cpp\&.
.SS "AbstractGame::~AbstractGame ()\fC [virtual]\fP"

.PP
Definition at line 12 of file AbstractGame\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void AbstractGame::_initializeGlew ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 62 of file AbstractGame\&.cpp\&.
.SS "void AbstractGame::_initializeRenderer ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 69 of file AbstractGame\&.cpp\&.
.SS "virtual void AbstractGame::_initializeScene ()\fC [protected]\fP, \fC [pure virtual]\fP"

.PP
Implemented in \fBdemo::MGEDemo\fP, \fBMyEngine::MGEDemo\fP, and \fBMyGame::MGEDemo\fP\&.
.SS "void AbstractGame::_initializeWindow ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
SETUP\&. 
.PP
Definition at line 33 of file AbstractGame\&.cpp\&.
.SS "void AbstractGame::_initializeWorld ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 77 of file AbstractGame\&.cpp\&.
.SS "void AbstractGame::_printVersionInfo ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 40 of file AbstractGame\&.cpp\&.
.SS "void AbstractGame::_processEvents ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 137 of file AbstractGame\&.cpp\&.
.SS "void AbstractGame::_render ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBdemo::MGEDemo\fP, \fBMyEngine::MGEDemo\fP, and \fBMyGame::MGEDemo\fP\&.
.PP
Definition at line 133 of file AbstractGame\&.cpp\&.
.SS "void AbstractGame::_update (float pStep)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 129 of file AbstractGame\&.cpp\&.
.SS "void AbstractGame::initialize ()\fC [virtual]\fP"

.PP
Reimplemented in \fBdemo::MGEDemo\fP, \fBMyEngine::MGEDemo\fP, and \fBMyGame::MGEDemo\fP\&.
.PP
Definition at line 20 of file AbstractGame\&.cpp\&.
.SS "void AbstractGame::run ()\fC [virtual]\fP"

.PP
MAIN GAME LOOP\&. 
.PP
Definition at line 86 of file AbstractGame\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "float AbstractGame::_fps\fC [protected]\fP"

.PP
Definition at line 56 of file AbstractGame\&.hpp\&.
.SS "\fBRenderer\fP* AbstractGame::_renderer\fC [protected]\fP"

.PP
Definition at line 54 of file AbstractGame\&.hpp\&.
.SS "sf::RenderWindow* AbstractGame::_window\fC [protected]\fP"

.PP
Definition at line 53 of file AbstractGame\&.hpp\&.
.SS "\fBWorld\fP* AbstractGame::_world\fC [protected]\fP"

.PP
Definition at line 55 of file AbstractGame\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MGE from the source code\&.
