.TH "config" 3 "Mon Jan 1 2018" "MGE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
config
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "const std::string \fBMGE_MODEL_PATH\fP ('mge/models/')"
.br
.ti -1c
.RI "const std::string \fBMGE_TEXTURE_PATH\fP ('mge/textures/')"
.br
.ti -1c
.RI "const std::string \fBMGE_SHADER_PATH\fP ('mge/shaders/')"
.br
.ti -1c
.RI "const std::string \fBMGE_FONT_PATH\fP ('mge/fonts/')"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "const std::string config::MGE_FONT_PATH ('mge/fonts/')"

.SS "const std::string config::MGE_MODEL_PATH ('mge/models/')"

.SS "const std::string config::MGE_SHADER_PATH ('mge/shaders/')"

.SS "const std::string config::MGE_TEXTURE_PATH ('mge/textures/')"

.SH "Author"
.PP 
Generated automatically by Doxygen for MGE from the source code\&.
