.TH "GameObject" 3 "Mon Jan 1 2018" "MGE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameObject
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GameObject\&.hpp>\fP
.PP
Inherited by \fBCamera\fP, \fBLight\fP, and \fBWorld\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGameObject\fP (const std::string &pName=nullptr, const glm::vec3 &pPosition=glm::vec3(0\&.0f, 0\&.0f, 0\&.0f))"
.br
.ti -1c
.RI "virtual \fB~GameObject\fP ()"
.br
.ti -1c
.RI "void \fBsetName\fP (const std::string &pName)"
.br
.ti -1c
.RI "std::string \fBgetName\fP () const"
.br
.ti -1c
.RI "void \fBsetTransform\fP (const glm::mat4 &pTransform)"
.br
.ti -1c
.RI "const glm::mat4 & \fBgetTransform\fP () const"
.br
.ti -1c
.RI "void \fBsetLocalPosition\fP (glm::vec3 pPosition)"
.br
.ti -1c
.RI "glm::vec3 \fBgetLocalPosition\fP () const"
.br
.ti -1c
.RI "glm::vec3 \fBgetWorldPosition\fP () const"
.br
.ti -1c
.RI "glm::mat4 \fBgetWorldTransform\fP () const"
.br
.ti -1c
.RI "void \fBtranslate\fP (glm::vec3 pTranslation)"
.br
.ti -1c
.RI "void \fBrotate\fP (float pAngle, glm::vec3 pAxis)"
.br
.ti -1c
.RI "void \fBscale\fP (glm::vec3 pScale)"
.br
.ti -1c
.RI "void \fBsetMesh\fP (\fBMesh\fP *pMesh)"
.br
.ti -1c
.RI "\fBMesh\fP * \fBgetMesh\fP () const"
.br
.ti -1c
.RI "void \fBsetMaterial\fP (\fBAbstractMaterial\fP *pMaterial)"
.br
.ti -1c
.RI "\fBAbstractMaterial\fP * \fBgetMaterial\fP () const"
.br
.ti -1c
.RI "void \fBsetBehaviour\fP (\fBAbstractBehaviour\fP *pBehaviour)"
.br
.ti -1c
.RI "\fBAbstractBehaviour\fP * \fBgetBehaviour\fP () const"
.br
.ti -1c
.RI "virtual void \fBupdate\fP (float pStep)"
.br
.ti -1c
.RI "void \fBadd\fP (\fBGameObject\fP *pChild)"
.br
.ti -1c
.RI "void \fBremove\fP (\fBGameObject\fP *pChild)"
.br
.ti -1c
.RI "void \fBsetParent\fP (\fBGameObject\fP *pGameObject)"
.br
.ti -1c
.RI "\fBGameObject\fP * \fBgetParent\fP () const"
.br
.ti -1c
.RI "int \fBgetChildCount\fP () const"
.br
.ti -1c
.RI "\fBGameObject\fP * \fBgetChildAt\fP (int pIndex) const"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fB_innerAdd\fP (\fBGameObject\fP *pChild)"
.br
.ti -1c
.RI "void \fB_innerRemove\fP (\fBGameObject\fP *pChild)"
.br
.ti -1c
.RI "virtual void \fB_setWorldRecursively\fP (\fBWorld\fP *pWorld)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::string \fB_name\fP"
.br
.ti -1c
.RI "glm::mat4 \fB_transform\fP"
.br
.ti -1c
.RI "\fBGameObject\fP * \fB_parent\fP"
.br
.ti -1c
.RI "std::vector< \fBGameObject\fP * > \fB_children\fP"
.br
.ti -1c
.RI "\fBMesh\fP * \fB_mesh\fP"
.br
.ti -1c
.RI "\fBAbstractBehaviour\fP * \fB_behaviour\fP"
.br
.ti -1c
.RI "\fBAbstractMaterial\fP * \fB_material\fP"
.br
.ti -1c
.RI "\fBWorld\fP * \fB_world\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A \fBGameObject\fP wraps all data required to display an object, but knows nothing about OpenGL or rendering\&. 
.PP
Definition at line 16 of file GameObject\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GameObject::GameObject (const std::string & pName = \fCnullptr\fP, const glm::vec3 & pPosition = \fCglm::vec3( 0\&.0f, 0\&.0f, 0\&.0f )\fP)"

.PP
Definition at line 5 of file GameObject\&.cpp\&.
.SS "GameObject::~GameObject ()\fC [virtual]\fP"

.PP
Definition at line 12 of file GameObject\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void GameObject::_innerAdd (\fBGameObject\fP * pChild)\fC [protected]\fP"

.PP
Definition at line 121 of file GameObject\&.cpp\&.
.SS "void GameObject::_innerRemove (\fBGameObject\fP * pChild)\fC [protected]\fP"

.PP
Definition at line 111 of file GameObject\&.cpp\&.
.SS "void GameObject::_setWorldRecursively (\fBWorld\fP * pWorld)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBLight\fP\&.
.PP
Definition at line 183 of file GameObject\&.cpp\&.
.SS "void GameObject::add (\fBGameObject\fP * pChild)"

.PP
Definition at line 127 of file GameObject\&.cpp\&.
.SS "\fBAbstractBehaviour\fP * GameObject::getBehaviour () const"

.PP
Definition at line 82 of file GameObject\&.cpp\&.
.SS "\fBGameObject\fP * GameObject::getChildAt (int pIndex) const"

.PP
Definition at line 195 of file GameObject\&.cpp\&.
.SS "int GameObject::getChildCount () const"

.PP
Definition at line 191 of file GameObject\&.cpp\&.
.SS "glm::vec3 GameObject::getLocalPosition () const"

.PP
Definition at line 51 of file GameObject\&.cpp\&.
.SS "\fBAbstractMaterial\fP * GameObject::getMaterial () const"

.PP
Definition at line 61 of file GameObject\&.cpp\&.
.SS "\fBMesh\fP * GameObject::getMesh () const"

.PP
Definition at line 71 of file GameObject\&.cpp\&.
.SS "std::string GameObject::getName () const"

.PP
Definition at line 31 of file GameObject\&.cpp\&.
.SS "\fBGameObject\fP * GameObject::getParent () const"

.PP
Definition at line 135 of file GameObject\&.cpp\&.
.SS "const glm::mat4 & GameObject::getTransform () const"

.PP
Definition at line 41 of file GameObject\&.cpp\&.
.SS "glm::vec3 GameObject::getWorldPosition () const"

.PP
Definition at line 142 of file GameObject\&.cpp\&.
.SS "glm::mat4 GameObject::getWorldTransform () const"

.PP
Definition at line 148 of file GameObject\&.cpp\&.
.SS "void GameObject::remove (\fBGameObject\fP * pChild)"

.PP
Definition at line 131 of file GameObject\&.cpp\&.
.SS "void GameObject::rotate (float pAngle, glm::vec3 pAxis)"

.PP
Definition at line 166 of file GameObject\&.cpp\&.
.SS "void GameObject::scale (glm::vec3 pScale)"

.PP
Definition at line 161 of file GameObject\&.cpp\&.
.SS "void GameObject::setBehaviour (\fBAbstractBehaviour\fP * pBehaviour)"

.PP
Definition at line 76 of file GameObject\&.cpp\&.
.SS "void GameObject::setLocalPosition (glm::vec3 pPosition)"

.PP
Definition at line 46 of file GameObject\&.cpp\&.
.SS "void GameObject::setMaterial (\fBAbstractMaterial\fP * pMaterial)"

.PP
Definition at line 56 of file GameObject\&.cpp\&.
.SS "void GameObject::setMesh (\fBMesh\fP * pMesh)"

.PP
Definition at line 66 of file GameObject\&.cpp\&.
.SS "void GameObject::setName (const std::string & pName)"

.PP
Definition at line 26 of file GameObject\&.cpp\&.
.SS "void GameObject::setParent (\fBGameObject\fP * pGameObject)"

.PP
Definition at line 87 of file GameObject\&.cpp\&.
.SS "void GameObject::setTransform (const glm::mat4 & pTransform)"

.PP
Definition at line 36 of file GameObject\&.cpp\&.
.SS "void GameObject::translate (glm::vec3 pTranslation)"

.PP
Definition at line 156 of file GameObject\&.cpp\&.
.SS "void GameObject::update (float pStep)\fC [virtual]\fP"

.PP
Definition at line 171 of file GameObject\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBAbstractBehaviour\fP* GameObject::_behaviour\fC [protected]\fP"

.PP
Definition at line 79 of file GameObject\&.hpp\&.
.SS "std::vector<\fBGameObject\fP*> GameObject::_children\fC [protected]\fP"

.PP
Definition at line 76 of file GameObject\&.hpp\&.
.SS "\fBAbstractMaterial\fP* GameObject::_material\fC [protected]\fP"

.PP
Definition at line 80 of file GameObject\&.hpp\&.
.SS "\fBMesh\fP* GameObject::_mesh\fC [protected]\fP"

.PP
Definition at line 78 of file GameObject\&.hpp\&.
.SS "std::string GameObject::_name\fC [protected]\fP"

.PP
Definition at line 72 of file GameObject\&.hpp\&.
.SS "\fBGameObject\fP* GameObject::_parent\fC [protected]\fP"

.PP
Definition at line 75 of file GameObject\&.hpp\&.
.SS "glm::mat4 GameObject::_transform\fC [protected]\fP"

.PP
Definition at line 73 of file GameObject\&.hpp\&.
.SS "\fBWorld\fP* GameObject::_world\fC [protected]\fP"

.PP
Definition at line 81 of file GameObject\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MGE from the source code\&.
