.TH "F:/Uni/2.2/3D Rendering/mge_v18_student_version(3)/mge_v18_student_version/src/glm.hpp" 3 "Mon Jan 1 2018" "MGE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/Uni/2.2/3D Rendering/mge_v18_student_version(3)/mge_v18_student_version/src/glm.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <glm/glm\&.hpp>\fP
.br
\fC#include <glm/ext\&.hpp>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGLM_FORCE_RADIANS\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &out, const glm::ivec2 &v)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &out, const glm::uvec3 &v)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &out, const glm::vec2 &v)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &out, const glm::vec3 &v)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &out, const glm::vec4 &v)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &out, const glm::quat &q)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &out, const glm::mat4 &m)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define GLM_FORCE_RADIANS"

.PP
Definition at line 7 of file glm\&.hpp\&.
.SH "Function Documentation"
.PP 
.SS "std::ostream& operator<< (std::ostream & out, const glm::ivec2 & v)\fC [inline]\fP"

.PP
Definition at line 20 of file glm\&.hpp\&.
.SS "std::ostream& operator<< (std::ostream & out, const glm::uvec3 & v)\fC [inline]\fP"

.PP
Definition at line 25 of file glm\&.hpp\&.
.SS "std::ostream& operator<< (std::ostream & out, const glm::vec2 & v)\fC [inline]\fP"

.PP
Definition at line 30 of file glm\&.hpp\&.
.SS "std::ostream& operator<< (std::ostream & out, const glm::vec3 & v)\fC [inline]\fP"

.PP
Definition at line 35 of file glm\&.hpp\&.
.SS "std::ostream& operator<< (std::ostream & out, const glm::vec4 & v)\fC [inline]\fP"

.PP
Definition at line 40 of file glm\&.hpp\&.
.SS "std::ostream& operator<< (std::ostream & out, const glm::quat & q)\fC [inline]\fP"

.PP
Definition at line 45 of file glm\&.hpp\&.
.SS "std::ostream& operator<< (std::ostream & out, const glm::mat4 & m)\fC [inline]\fP"

.PP
Definition at line 50 of file glm\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MGE from the source code\&.
