.TH "KeysBehaviour" 3 "Mon Jan 1 2018" "MGE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KeysBehaviour
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <KeysBehaviour\&.hpp>\fP
.PP
Inherits \fBAbstractBehaviour\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKeysBehaviour\fP (float pMoveSpeed=5, float pTurnSpeed=45)"
.br
.ti -1c
.RI "virtual \fB~KeysBehaviour\fP ()"
.br
.ti -1c
.RI "virtual void \fBupdate\fP (float pStep)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBKeysBehaviour\fP allows you to move an object using the keyboard in its own local space\&. Left right turns, forward back moves\&. 
.PP
Definition at line 10 of file KeysBehaviour\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "KeysBehaviour::KeysBehaviour (float pMoveSpeed = \fC5\fP, float pTurnSpeed = \fC45\fP)"

.PP
Definition at line 5 of file KeysBehaviour\&.cpp\&.
.SS "KeysBehaviour::~KeysBehaviour ()\fC [virtual]\fP"

.PP
Definition at line 9 of file KeysBehaviour\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void KeysBehaviour::update (float pStep)\fC [virtual]\fP"

.PP
Implements \fBAbstractBehaviour\fP\&.
.PP
Definition at line 13 of file KeysBehaviour\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MGE from the source code\&.
