.TH "F:/Uni/2.2/3D Rendering/mge_v18_student_version(3)/mge_v18_student_version/src/main.cpp" 3 "Mon Jan 1 2018" "MGE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/Uni/2.2/3D Rendering/mge_v18_student_version(3)/mge_v18_student_version/src/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'mge/core/AbstractGame\&.hpp'\fP
.br
\fC#include 'mge/MGEDemo\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Definition at line 23 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MGE from the source code\&.
