.TH "Mesh::FaceIndexTriplet" 3 "Mon Jan 1 2018" "MGE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mesh::FaceIndexTriplet
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Mesh\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFaceIndexTriplet\fP (unsigned pV, unsigned pUV, unsigned pN)"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBFaceIndexTriplet\fP other) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBv\fP"
.br
.ti -1c
.RI "unsigned \fBuv\fP"
.br
.ti -1c
.RI "unsigned \fBn\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 65 of file Mesh\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Mesh::FaceIndexTriplet::FaceIndexTriplet (unsigned pV, unsigned pUV, unsigned pN)\fC [inline]\fP"

.PP
Definition at line 70 of file Mesh\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool Mesh::FaceIndexTriplet::operator< (const \fBFaceIndexTriplet\fP other) const\fC [inline]\fP"

.PP
Definition at line 74 of file Mesh\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned Mesh::FaceIndexTriplet::n"

.PP
Definition at line 69 of file Mesh\&.hpp\&.
.SS "unsigned Mesh::FaceIndexTriplet::uv"

.PP
Definition at line 68 of file Mesh\&.hpp\&.
.SS "unsigned Mesh::FaceIndexTriplet::v"

.PP
Definition at line 67 of file Mesh\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MGE from the source code\&.
