.TH "MyEngineConfig" 3 "Mon Jan 1 2018" "MGE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MyEngineConfig
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "const std::string \fBMGE_MODEL_PATH\fP ('myEngine/models/')"
.br
.ti -1c
.RI "const std::string \fBMGE_TEXTURE_PATH\fP ('myEngine/textures/')"
.br
.ti -1c
.RI "const std::string \fBMGE_SHADER_PATH\fP ('myEngine/shaders/')"
.br
.ti -1c
.RI "const std::string \fBMGE_FONT_PATH\fP ('myEngine/fonts/')"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "const std::string MyEngineConfig::MGE_FONT_PATH ('myEngine/fonts/')"

.SS "const std::string MyEngineConfig::MGE_MODEL_PATH ('myEngine/models/')"

.SS "const std::string MyEngineConfig::MGE_SHADER_PATH ('myEngine/shaders/')"

.SS "const std::string MyEngineConfig::MGE_TEXTURE_PATH ('myEngine/textures/')"

.SH "Author"
.PP 
Generated automatically by Doxygen for MGE from the source code\&.
