.TH "MyEngine::MGEDemo" 3 "Mon Jan 1 2018" "MGE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MyEngine::MGEDemo
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MyEngine\&.hpp>\fP
.PP
Inherits \fBAbstractGame\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMGEDemo\fP ()"
.br
.ti -1c
.RI "virtual \fB~MGEDemo\fP ()"
.br
.ti -1c
.RI "virtual void \fBinitialize\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fB_initializeScene\fP ()"
.br
.ti -1c
.RI "virtual void \fB_render\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
An example subclass of \fBAbstractGame\fP showing how we can setup a scene\&. 
.PP
Definition at line 13 of file MyEngine\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MyEngine::MGEDemo::MGEDemo ()"

.PP
Definition at line 31 of file MyEngine\&.cpp\&.
.SS "MyEngine::MGEDemo::~MGEDemo ()\fC [virtual]\fP"

.PP
Definition at line 113 of file MyEngine\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void MyEngine::MGEDemo::_initializeScene ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBAbstractGame\fP\&.
.PP
Definition at line 46 of file MyEngine\&.cpp\&.
.SS "void MyEngine::MGEDemo::_render ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBAbstractGame\fP\&.
.PP
Definition at line 100 of file MyEngine\&.cpp\&.
.SS "void MyEngine::MGEDemo::initialize ()\fC [virtual]\fP"

.PP
Reimplemented from \fBAbstractGame\fP\&.
.PP
Definition at line 35 of file MyEngine\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MGE from the source code\&.
