.TH "F:/Uni/2.2/3D Rendering/mge_v18_student_version(3)/mge_v18_student_version/src/myEngine/MyEngineConfig.hpp" 3 "Mon Jan 1 2018" "MGE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/Uni/2.2/3D Rendering/mge_v18_student_version(3)/mge_v18_student_version/src/myEngine/MyEngineConfig.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMyEngineConfig\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "const std::string \fBMyEngineConfig::MGE_MODEL_PATH\fP ('myEngine/models/')"
.br
.ti -1c
.RI "const std::string \fBMyEngineConfig::MGE_TEXTURE_PATH\fP ('myEngine/textures/')"
.br
.ti -1c
.RI "const std::string \fBMyEngineConfig::MGE_SHADER_PATH\fP ('myEngine/shaders/')"
.br
.ti -1c
.RI "const std::string \fBMyEngineConfig::MGE_FONT_PATH\fP ('myEngine/fonts/')"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MGE from the source code\&.
