.TH "F:/Uni/2.2/3D Rendering/mge_v18_student_version(3)/mge_v18_student_version/src/myGame/MyGameConfig.hpp" 3 "Mon Jan 1 2018" "MGE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/Uni/2.2/3D Rendering/mge_v18_student_version(3)/mge_v18_student_version/src/myGame/MyGameConfig.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMyGame\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "const std::string \fBMyGame::MGE_MODEL_PATH\fP ('myGame/models/')"
.br
.ti -1c
.RI "const std::string \fBMyGame::MGE_TEXTURE_PATH\fP ('myGame/textures/')"
.br
.ti -1c
.RI "const std::string \fBMyGame::MGE_SHADER_PATH\fP ('myGame/shaders/')"
.br
.ti -1c
.RI "const std::string \fBMyGame::MGE_FONT_PATH\fP ('myGame/fonts/')"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MGE from the source code\&.
