.TH "RotatingBehaviour" 3 "Mon Jan 1 2018" "MGE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RotatingBehaviour
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RotatingBehaviour\&.hpp>\fP
.PP
Inherits \fBAbstractBehaviour\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRotatingBehaviour\fP ()"
.br
.ti -1c
.RI "virtual \fB~RotatingBehaviour\fP ()"
.br
.ti -1c
.RI "virtual void \fBupdate\fP (float pStep)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Simply rotates the object around its origin with a fixed speed\&. 
.PP
Definition at line 9 of file RotatingBehaviour\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RotatingBehaviour::RotatingBehaviour ()"

.PP
Definition at line 4 of file RotatingBehaviour\&.cpp\&.
.SS "RotatingBehaviour::~RotatingBehaviour ()\fC [virtual]\fP"

.PP
Definition at line 9 of file RotatingBehaviour\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void RotatingBehaviour::update (float pStep)\fC [virtual]\fP"

.PP
Implements \fBAbstractBehaviour\fP\&.
.PP
Definition at line 14 of file RotatingBehaviour\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MGE from the source code\&.
