.TH "World" 3 "Mon Jan 1 2018" "MGE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
World
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <World\&.hpp>\fP
.PP
Inherits \fBGameObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWorld\fP ()"
.br
.ti -1c
.RI "void \fBsetMainCamera\fP (\fBCamera\fP *pCamera)"
.br
.ti -1c
.RI "\fBCamera\fP * \fBgetMainCamera\fP ()"
.br
.ti -1c
.RI "void \fBregisterLight\fP (\fBLight\fP *pLight)"
.br
.ti -1c
.RI "void \fBunregisterLight\fP (\fBLight\fP *pLight)"
.br
.ti -1c
.RI "\fBLight\fP * \fBgetLightAt\fP (int pIndex)"
.br
.ti -1c
.RI "int \fBgetLightCount\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 9 of file World\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "World::World ()"

.PP
Definition at line 7 of file World\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBLight\fP * World::getLightAt (int pIndex)"

.PP
Definition at line 32 of file World\&.cpp\&.
.SS "int World::getLightCount ()"

.PP
Definition at line 36 of file World\&.cpp\&.
.SS "\fBCamera\fP * World::getMainCamera ()"

.PP
Definition at line 16 of file World\&.cpp\&.
.SS "void World::registerLight (\fBLight\fP * pLight)"

.PP
Definition at line 21 of file World\&.cpp\&.
.SS "void World::setMainCamera (\fBCamera\fP * pCamera)"

.PP
Definition at line 12 of file World\&.cpp\&.
.SS "void World::unregisterLight (\fBLight\fP * pLight)"

.PP
Definition at line 26 of file World\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MGE from the source code\&.
